pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/kavinayaravi/AutoDeployX.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("autodeployx-app:${env.BUILD_NUMBER}", "./app")
                }
            }
        }

        stage('Test Docker Image') {
            steps {
                echo "Placeholder for running tests"
            }
        }
    }
}
